window.SHIMEJI_SHOUTS = {
  encouragement: [
    'Keep going!', 'You got this!', 'Keep it up!', 'Great job!', 'Nice work!',
    'Stay focused!', 'Almost there!', "You're doing great!", "Don't give up!",
    "Let's go!", 'Amazing!', 'Fantastic!', 'Brilliant!', 'Awesome!',
    'Way to go!', "That's the spirit!", 'Keep pushing!', 'Never stop!',
    'You rock!', 'Superstar!', 'Legend!', "I'm proud of you!",
    'One step at a time!', 'Progress!', 'Believe in yourself!',
    'Champion!', 'Unstoppable!', "That's how it's done!", 'Perfection!',
    'So close!', 'Just a bit more!', "I believe in you!", 'Hero!',
    'You inspire me!', 'Keep shining!', 'On fire!', 'Nailed it!',
    'Top notch!', 'Spectacular!', "You're a star!", 'Impressive!',
    'Молодец!', 'Давай-давай!', 'Так держать!', 'Ты можешь!',
    'Отлично!', 'Супер!', 'Круто!', 'Красавчик!', 'Вперёд!',
    'Не останавливайся!', 'Продолжай!', 'Здорово!', 'Умничка!',
    'Чемпион!', 'Блестяще!', 'Ещё чуть-чуть!', 'Ты лучший!',
    'Горжусь тобой!', 'Шикарно!', 'Верю в тебя!',
  ],
  flying: [
    "I'm flying!", 'Woohoo!', 'Whee!', "That's good!", 'Weee!', 'Yay!',
    "Let's goo!", 'Up up and away!', 'To infinity!', 'Wheeeee!',
    'Higher!', 'Soaring!', 'Like a bird!', 'Freedom!', 'Zoom!',
    'Look at me!', 'No fear!', 'Sky is the limit!', 'Turbo mode!',
    'Catch me if you can!', 'Flying high!', 'Wind in my face!',
    'Like a rocket!', 'Supersonic!', 'Warp speed!', 'Here I come!',
    'Watch out below!', 'Air time!', 'Wings activated!',
    'Полетели!', 'Вжух!', 'Лечу!', 'Выше!', 'Как птица!',
    'Пиу-пиу!', 'На взлёт!', 'У-у-у!', 'Догони!', 'Вперёд!',
    'Как ракета!', 'Ветер!', 'Свобода!',
  ],
  thinking: [
    'Hmm...', 'What if...', 'Interesting...', 'I wonder...',
    'Let me think...', 'Curious...', 'Maybe...', 'Perhaps...',
    'That makes sense...', 'Wait a moment...', 'Oh!', 'Aha!',
    'I see...', 'So that is how...', 'Makes you think...', 'Huh.',
    'Could it be...', 'Really?', 'No way...', 'Fascinating...',
    'I knew it!', 'Plot twist!', 'Deep thoughts...', 'Eureka!',
    'Hold on...', 'But why...', 'Elementary!', 'Suspicious...',
    'Big brain time...', 'Let me ponder...', 'Actually...',
    'Хмм...', 'А что если...', 'Интересно...', 'Думаю...',
    'Подожди-ка...', 'Любопытно...', 'Может быть...', 'Ого!',
    'Вот это да...', 'Ага!', 'Хм, а ведь...', 'Так-так...',
    'Эврика!', 'Подозрительно...', 'А вдруг...', 'Секундочку...',
    'Вот оно что!', 'Минуточку...', 'Логично...',
  ],
  dragging: [
    'Brrr!', 'Meh...', 'Why me?!', 'And now...', 'Where?!', 'Whoops!',
    'Ouch!', 'Caramba!', 'Hey!', 'Woah!', 'Put me down!', 'Help!',
    'Not again!', 'Easy there!', 'Careful!', 'Watch it!',
    'Where are we going?!', 'Unhand me!', 'Noooo!', 'This is fine...',
    'I can walk!', "I didn't sign up for this!", 'Gentle!', 'Oh no!',
    'Is this a ride?', 'Wheee... I guess?', 'I feel sick...',
    'Emergency landing!', 'Mayday!', "I'll remember this!",
    'My dignity!', 'Rude!', 'Excuse me?!', 'Personal space!',
    'Куда?!', 'Ааааа!', 'Эй!', 'Отпусти!', 'Помогите!',
    'Осторожнее!', 'Не надо!', 'Куда несёшь?!', 'Я сам могу!',
    'Полегче!', 'Зачем?!', 'Верни меня!', 'Грубиян!',
    'Мне плохо...', 'Я запомню это!', 'Ну и ну!',
  ],
  tired: [
    'So tired...', 'Need rest...', 'Zzz...', '*yawn*', 'Exhausted...',
    'Five more min...', 'Sleepy...', 'Can barely stand...', 'Energy low...',
    'Need coffee...', 'Where is my bed...', '*stretches*', 'So heavy...',
    'Break time?', 'My legs...', 'Long day...', 'Running on empty...',
    'Battery: 1%...', 'Recharging...', 'System shutting down...',
    'Just a quick nap...', 'Low power mode...', "Can't... move...",
    'Устал...', 'Отдохну...', 'Хочу спать...', 'Ещё минутку...',
    'Еле стою...', 'Нужен перерыв...', 'Уф...', 'Мои ножки...',
    'Сил нет...', 'Когда отдых...', 'Спа-а-ать...',
    'Батарейка села...', 'Перезарядка...', 'Только не вставать...',
  ],
  fallen: [
    'Ouch!', 'Ow!', 'Oof!', 'Owie!', 'That hurt!', 'My back!',
    'I meant to do that!', 'Gravity wins...', '10/10 landing!',
    'Smooth...', 'Again?!', 'Why...', 'Floor, my old friend...',
    'Ай!', 'Больно!', 'Ух!', 'Это было больно...', 'Бум!',
    'Опять?!', 'Ой-ой-ой!', 'Блин!',
  ],
  cursorCatch: [
    'Gotcha!', 'Caught you!', 'Ahaa!', 'There you are!', 'Got you!',
    'Mine now!', 'Tag!', "Can't escape!", 'Found you!', 'Hehe!',
    "You're it!", 'Grabbed ya!', 'No running!', 'Surprise!',
    'Too slow!', 'Sneak attack!', "I'm fast!", 'Clingy mode!',
    'Попался!', 'Поймал!', 'Агааа!', 'Вот и ты!', 'Мой!',
    'Держу!', 'Никуда не денешься!', 'Ха-ха!', 'Тебя нашёл!',
    'Не убежишь!', 'Сюрприз!', 'Быстрый я!',
  ],
  hop: [
    'Hop!', 'Whee!', 'Boing!', 'Jump!', 'Hup!', 'Yip!',
    'Sproing!', 'Bounce!', 'Woop!', 'Haha!', 'La-la!',
    'Hippity hop!', 'Boop!', 'Up!', 'Again!', 'Weee!',
    'Прыг!', 'Скок!', 'Хоп!', 'Ля-ля!', 'Прыг-скок!',
    'Бум!', 'Ещё!', 'Выше!', 'Ух!',
  ],
  houseInside: [
    'Zzz...', 'Z-z-z-z...', '*sleeping*', 'So cozy...', 'Home sweet home!',
    '*cooking*', 'Smells good!', '*playing games*', 'One more level...',
    '*reading*', 'Warm and toasty!', 'My place!',
    '*humming*', 'Tea time!', 'Peace and quiet...', 'Relaxing...',
    'Nothing like home!', '*snoring*', 'Best nap ever...', '*munching*',
    'What a day...', 'Finally home!', 'Safe and sound!', '*whistling*',
    'Уютненько...', 'Тут тепло...', 'Ещё 5 минуточек...',
    '*готовит*', 'Z-z-z...', 'Мой домик!', '*играет*', 'Чаёк...',
    'Покой...', '*читает*', 'Тишина...', 'Как хорошо дома!',
    '*храпит*', 'Наконец-то дома!', 'В безопасности!',
  ],
  houseClick: [
    "That's my house!", 'My home!', 'Cozy, right?', 'Nice place!',
    "Isn't it cute?", 'Home!', 'I built it myself!', 'Welcome!',
    'Мой домик!', 'Уютный, да?', 'Нравится?', 'Моё жилище!',
    'Сам построил!', 'Добро пожаловать!',
  ],
  houseClickInside: [
    "I'm resting...", "Don't bother me!", 'Go away!', 'Z-z-z-z...',
    'Busy!', "I'm sleeping!", 'Not now!', 'Come back later!',
    'Private time!', 'Occupied!', 'Shh!', "Can't you see I'm busy?",
    'Leave me alone...', 'Knock first!', "I'm not here!",
    'Отстань!', 'Я сплю...', 'Занят!', 'Не трогай!',
    'Своими делами займись!', 'Не сейчас!', 'Приходи позже!',
    'Тс-с-с!', 'Я отдыхаю...', 'Не мешайте...', 'Стучаться надо!',
    'Меня нет дома!',
  ],
  petReaction: [
    'Hehe!', 'That tickles!', 'Aww!', '*purrs*', 'More please!',
    'Nice!', 'So warm!', 'Comfy!', "That's the spot!",
    'Хе-хе!', 'Щекотно!', 'Ещё!', 'Приятно!', '*мурчит*',
  ],
  welcomeBack: [
    'Oh hey!', "You're back!", 'Missed you!', 'Hi again!', 'Welcome back!',
    'There you are!', 'Long time no see!', 'Hey!', "Yay, you're here!",
    'Finally!', 'I waited!', 'Did you miss me?', 'Hello again!',
    'Oh!', "Where'd you go?", 'Back already?', 'Missed me?',
    'О, привет!', 'Ты вернулся!', 'Скучал!', 'С возвращением!',
    'Наконец-то!', 'А вот и ты!', 'Привет!', 'Я ждал!',
    'Ты по мне скучал?', 'Давно не виделись!', 'О!', 'Куда пропал?',
    'Уже вернулся?', 'Скучал по мне?', 'Привет-привет!',
  ],
};
